after_script: greenkeeper-lockfile-upload

before_install: npm i -g greenkeeper-lockfile npm@latest

before_script: greenkeeper-lockfile-update

install: npm i && npm i budgie ts-budgie typescript --no-save

language: node_js

node_js:
  - "node"
  - "8"

script:
  npm run verify
